### ISSUE TITLE
Fails to clean up temp directory properly on Windows

### ISSUE THREAD

**Issue by rcook** [rcook/upload-haddocks#2]
```
PS C:\src\hidden-char> upload-haddocks.exe --creds C:\sr\upload\credentials.json
* Generate
hidden-char-0.1.0.2: unregistering
hidden-char-0.1.0.2: configure (lib)
Configuring hidden-char-0.1.0.2...
hidden-char-0.1.0.2: build (lib)
Preprocessing library hidden-char-0.1.0.2...
[2 of 2] Compiling System.IO.HiddenChar ( src\System\IO\HiddenChar.hs, .stack-work\dist\b7fec021\build\System\IO\HiddenC
har.o ) [.stack-work\dist\b7fec021\build\autogen\cabal_macros.h changed]
hidden-char-0.1.0.2: haddock
Running Haddock for hidden-char-0.1.0.2...
Preprocessing library hidden-char-0.1.0.2...
Haddock coverage:
 100% (  2 /  2) in 'System.IO.HiddenChar.Windows'
 100% (  2 /  2) in 'System.IO.HiddenChar'
Documentation created:
.\.stack-work\dist\b7fec021\doc\html\hidden-char\.\index.html
hidden-char-0.1.0.2: copy/register
Installing library in
C:\src\hidden-char\.stack-work\install\4338eac8\lib\x86_64-windows-ghc-8.0.1\hidden-char-0.1.0.2-3M8sdJuYLNsGl87jJ8bG72
Registering hidden-char-0.1.0.2...
Updating Haddock index for local packages in
C:\src\hidden-char\.stack-work\install\4338eac8\doc\index.html
Updating Haddock index for local packages and dependencies in
C:\src\hidden-char\.stack-work\install\4338eac8\doc\all\index.html
Haddock index for snapshot packages already up to date at:
C:\sr\snapshots\e90768aa\doc\index.html
* Copy
* Munge
* Pack
Traceback (most recent call last):
  File "c:\bin\python-2.7.13.amd64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\bin\python-2.7.13.amd64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\rcook\AppData\Roaming\Python\Scripts\upload-haddocks.exe\__main__.py", line 9, in <module>
  File "C:\Users\rcook\AppData\Roaming\Python\Python27\site-packages\uploadhaddocks\__main__.py", line 58, in _main
    upload_haddocks(args.credentials_path, args.project_dir)
  File "C:\Users\rcook\AppData\Roaming\Python\Python27\site-packages\uploadhaddocks\util.py", line 149, in upload_haddoc
ks
    _upload_archive(user_name, password, tar_path, package_name, package_version)
  File "c:\bin\python-2.7.13.amd64\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\rcook\AppData\Roaming\Python\Python27\site-packages\pyprelude\temp_util.py", line 25, in _temp_helper
    obj.close()
  File "C:\Users\rcook\AppData\Roaming\Python\Python27\site-packages\pyprelude\temp_util.py", line 36, in close
    remove_dir(self._path)
  File "C:\Users\rcook\AppData\Roaming\Python\Python27\site-packages\pyprelude\file_system.py", line 43, in remove_dir
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'c:\\users\\rcook\\appdata\\local\\temp\\tmp4vqzbx'
```

**Comment by rcook** [comment]
This looks like a problem with `remove_dir`: https://github.com/rcook/pyprelude/blob/master/pyprelude/file_system.py#L43

**Comment by rcook** [comment]
There is a legit bug: the call to the (deprecated) `file` function does not close the file handle and prevents the clean-up from happening.
